script: 'CODECLIMATE_REPO_TOKEN=9fa3f4fd74e7a4db6ed2bb95844cafd8f31ceddcbcbfd7a99129d2718ba0513d bundle exec rake neo4j:install[community,1.9.8] neo4j:start spec --trace'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
